theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

title: Christopher Bonhage
author: Christopher Bonhage
email: me@christopherbonhage.com
github_username: meeq
twitter_username: meeq64
linkedin_username: christopher-bonhage
description: ''

google_analytics: UA-101038319-1
google_adsense: ca-pub-6803706372264508

header_pages:
  - index.md
  - posts.html
  - resume.md
